<a href="https://colab.research.google.com/github/20146467/TRITUENHANTAO/blob/main/AI_24_03_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#ANN

In [ ]:
pip install sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from sklearn.linear_model import Perceptron
x = [[0,0],[1,0],[0,1],[1,1]]
y = [0,1,1,1]
model = Perceptron()
model.fit(x,y)
model.score(x,y)


1.0

In [ ]:
from sklearn.linear_model import Perceptron
x1 = [[-0.5, -0.5],[10,-2],[-1, 0.8],[3,5],[1,0.2],[-0.1,0.5]]
y1 = model.predict(x1)
model = Perceptron()
model.fit(x1,y1)
model.score(x1,y1)

1.0

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [ ]:
model = Perceptron(max_iter =40, eta0 = 0.1, random_state = 0) #max_iter: so lan hoc, eta0: toc do hoc,radom  
model.fit(X_train, y_train)
y_pred = model.predict(X_test_std)
print(y_pred)
print(y_test)
print('Do chinh xac cua mo hinh:', accuracy_score(y_test,y_pred))


NameError: ignored

In [ ]:
import pandas as pd
import numpy as np

dataframe = pd.read_csv('crabs.csv')
dataframe.head()
crab_B = dataframe
crab_B.sex = crab_B.sex.apply(lambda x: x.replace("M","1"))
crab_B.sex = crab_B.sex.apply(lambda x: x.replace("F","0"))
print(crab_B)

    speies sex  index  fontallip  rearwidth  length  width  depth
0        B   1      1        8.1        6.7    16.1   19.0    7.0
1        B   1      2        8.8        7.7    18.1   20.8    7.4
2        B   1      3        9.2        7.8    19.0   22.4    7.7
3        B   1      4        9.6        7.9    20.1   23.1    8.2
4        B   1      5        9.8        8.0    20.3   23.0    8.2
..     ...  ..    ...        ...        ...     ...    ...    ...
195      O   0     46       21.4       18.0    41.2   46.2   18.7
196      O   0     47       21.7       17.1    41.7   47.2   19.6
197      O   0     48       21.9       17.2    42.6   47.4   19.5
198      O   0     49       22.5       17.2    43.0   48.7   19.8
199      O   0     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 8 columns]


In [ ]:
data_replaced_1=data['speies'].replace(["O", "B"], [1, 0]).head(150)
data_replaced_1

0      0
1      0
2      0
3      0
4      0
      ..
145    1
146    1
147    1
148    1
149    1
Name: speies, Length: 150, dtype: int64

In [ ]:
x = crab_B.drop(['speies','sex','index'],axis = 1)
print(x)
y = crab_B.sex
print(y)

     fontallip  rearwidth  length  width  depth
0          8.1        6.7    16.1   19.0    7.0
1          8.8        7.7    18.1   20.8    7.4
2          9.2        7.8    19.0   22.4    7.7
3          9.6        7.9    20.1   23.1    8.2
4          9.8        8.0    20.3   23.0    8.2
..         ...        ...     ...    ...    ...
195       21.4       18.0    41.2   46.2   18.7
196       21.7       17.1    41.7   47.2   19.6
197       21.9       17.2    42.6   47.4   19.5
198       22.5       17.2    43.0   48.7   19.8
199       23.1       20.2    46.2   52.5   21.1

[200 rows x 5 columns]
0      1
1      1
2      1
3      1
4      1
      ..
195    0
196    0
197    0
198    0
199    0
Name: sex, Length: 200, dtype: object


In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)
sc = StandardScaler()
sc.fit(x_train)
x_train = sc.transform(x_train)
x_test = sc.transform(x_test)
model = Perceptron(max_iter = 1000, eta0 = 0.2, random_state = 0)
#model: số lần học
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
print(y_pred)
print(y_test)
print("Độ chính xác của mô hình: ", accuracy_score(y_test, y_pred))

['1' '0' '1' '1' '0' '1' '1' '0' '0' '1' '0' '1' '1' '0' '1' '1' '1' '0'
 '0' '0' '1' '1' '0' '1' '0' '1' '1' '1' '0' '0' '0' '0' '0' '0' '1' '0'
 '1' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '1' '0' '0' '0' '0' '1'
 '0' '0' '1' '1' '0' '0']
141    1
9      1
33     1
4      1
169    0
103    1
7      1
72     0
168    0
111    1
11     1
16     1
3      1
165    0
124    1
136    1
123    1
156    0
151    0
102    1
34     1
116    1
94     0
23     1
191    0
105    1
132    1
37     1
106    1
62     0
73     0
160    0
78     0
56     0
30     1
187    0
121    1
84     0
154    0
89     0
178    0
92     0
60     0
199    0
52     0
87     0
109    1
163    0
21     1
179    0
67     0
184    0
180    0
101    1
51     0
55     0
49     1
134    1
90     0
83     0
Name: sex, dtype: object
Độ chính xác của mô hình:  0.9166666666666666
